#!/usr/bin/env python3
"""
send_strokes.py — Send Expresii stroke commands to a running Expresii Paint app.

Expresii Paint (v2026.04.30+) runs a local web API server on port 9000 by default.
This script sends an XST-format stroke file to it via the /confirm-ajax endpoint.

Usage:
    # Send a pre-made .xst file
    python send_strokes.py painting.xst

    # Build strokes inline
    python send_strokes.py --host 192.168.1.50 --port 9000 --command 'B 4' --command 'w 0.5'

    # Build strokes from a list of (x, y, pressure) waypoints
    python send_strokes.py --size 4 --wetness 0.5 --stroke -2.5,-2.8,0 -2.4,-2.7,0.15

    # Check if the server is up
    python send_strokes.py --ping
"""

import argparse
import http.client
import json
import socket
import sys
import urllib.parse
from pathlib import Path


def ping(host: str, port: int, timeout: float = 2.0) -> bool:
    """Check if Expresii's stroke server is reachable on host:port."""
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except (ConnectionRefusedError, socket.timeout, OSError):
        return False


def send_xst(host: str, port: int, xst_text: str, timeout: float = 10.0) -> dict:
    """
    POST the XST text to <host>:<port>/confirm-ajax as a multipart form.
    Returns a dict with 'ok' (bool), 'status' (HTTP code or 'no_response'),
    'sent_chars' (int), and optional 'error' (str).
    """
    boundary = "----amamiBoundary" + str(hash(xst_text) & 0xFFFFFFFF)
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="message"\r\n\r\n'
        f"{xst_text}\r\n"
        f"--{boundary}--\r\n"
    ).encode("utf-8")

    try:
        conn = http.client.HTTPConnection(host, port, timeout=timeout)
        headers = {
            "Content-Type": f"multipart/form-data; boundary={boundary}",
            "Content-Length": str(len(body)),
        }
        conn.request("POST", "/confirm-ajax", body=body, headers=headers)
        resp = conn.getresponse()
        resp_body = resp.read().decode("utf-8", errors="replace")
        conn.close()
        return {
            "ok": 200 <= resp.status < 300,
            "status": resp.status,
            "sent_chars": len(xst_text),
            "response": resp_body[:500],
        }
    except (ConnectionRefusedError, socket.timeout, OSError) as e:
        return {"ok": False, "status": "no_response", "error": str(e)}


def build_stroke_command(waypoints: list, size: float, wetness: float, scratch: float,
                         z_base: float = 0.0, tilt_y: float = 0.0, tilt_x: float = 0.0,
                         barrel_rot: float = 0.0) -> str:
    """
    Build a minimal XST script: setup (size/wetness/scratch) + stroke frames from waypoints.

    waypoints: list of (x, y, pressure) tuples. Pressure range [0.0, 1.0].
    z for each frame is auto-derived from pressure using z = 0.0625 - 0.125 * pressure
    (the empirically correct coupling for a flat stroke). Pass waypoints as plain
    (x, y, pressure) and the helper will fill in the right z for each frame.
    """
    lines = [
        "# Generated by expresii-brush skill",
        f"B {size:.5f}",
        f"w {wetness:.5f}",
        f"i {scratch:.5f}",
    ]
    for x, y, p in waypoints:
        z = 0.0625 - 0.125 * p
        lines.append(f"s {x:.5f} {y:.5f} {z:.5f} {tilt_y:.5f} {tilt_x:.5f} {barrel_rot:.5f} {p:.5f}")
    return "\n".join(lines) + "\n"


def parse_waypoint(s: str) -> tuple:
    """Parse 'x,y,p' or 'x,y' (pressure defaults to 0.5) into a tuple."""
    parts = s.split(",")
    if len(parts) == 2:
        x, y = float(parts[0]), float(parts[1])
        return (x, y, 0.5)
    elif len(parts) == 3:
        return (float(parts[0]), float(parts[1]), float(parts[2]))
    else:
        raise ValueError(f"Bad waypoint '{s}': expected 'x,y' or 'x,y,pressure'")


def main():
    ap = argparse.ArgumentParser(
        description="Send XST stroke commands to an Expresii Paint stroke server.",
        epilog="Pass a .xst file OR use --command/--stroke to build inline.",
    )
    ap.add_argument("xst_file", nargs="?", help="Path to a pre-made .xst file to send")
    ap.add_argument("--host", default="127.0.0.1", help="Server host (default: 127.0.0.1)")
    ap.add_argument("--port", type=int, default=9000, help="Server port (default: 9000)")
    ap.add_argument("--timeout", type=float, default=10.0, help="HTTP timeout in seconds (default: 10)")
    ap.add_argument("--ping", action="store_true", help="Just check if the server is up; exit 0 if yes")
    # Inline stroke building
    ap.add_argument("--size", type=float, default=4.0, help="Brush size 1-7 (default: 4)")
    ap.add_argument("--wetness", type=float, default=0.5, help="Brush wetness 0.01-1.0 (default: 0.5)")
    ap.add_argument("--scratch", type=float, default=0.5, help="Brush scratchiness 0.0-1.0 (default: 0.5)")
    ap.add_argument("--command", action="append", default=[], help="Add a raw XST line (e.g. 'B 4'). Repeatable.")
    ap.add_argument("--stroke", action="append", default=[],
                    help="Add a stroke waypoint 'x,y,pressure'. Pressure defaults to 0.5. Repeatable. "
                         "Use the = form (--stroke=-1,-1,0) when values are negative.")
    ap.add_argument("--json", action="store_true", help="Emit a machine-readable JSON result on stdout")
    args = ap.parse_args()

    if args.ping:
        up = ping(args.host, args.port)
        result = {"ok": up, "host": args.host, "port": args.port}
        if args.json:
            print(json.dumps(result))
        else:
            print(f"{'UP' if up else 'DOWN'}  {args.host}:{args.port}")
        sys.exit(0 if up else 1)

    # Build the XST text
    if args.xst_file:
        path = Path(args.xst_file)
        if not path.exists():
            print(f"error: file not found: {args.xst_file}", file=sys.stderr)
            sys.exit(2)
        xst_text = path.read_text(encoding="utf-8")
    elif args.command or args.stroke:
        lines = list(args.command)
        if args.stroke:
            try:
                waypoints = [parse_waypoint(s) for s in args.stroke]
            except ValueError as e:
                print(f"error: {e}", file=sys.stderr)
                sys.exit(2)
            lines.append(build_stroke_command(waypoints, args.size, args.wetness, args.scratch))
        xst_text = "\n".join(lines) + "\n"
    else:
        ap.error("provide an XST file or at least one --command/--stroke")

    # Send it
    result = send_xst(args.host, args.port, xst_text, args.timeout)
    result["host"] = args.host
    result["port"] = args.port

    if args.json:
        print(json.dumps(result))
    else:
        if result["ok"]:
            print(f"OK  sent {result['sent_chars']} chars to {args.host}:{args.port} (HTTP {result['status']})")
        else:
            print(f"FAIL  {result.get('status', '?')}  {result.get('error', '')}", file=sys.stderr)
            if "response" in result:
                print(result["response"], file=sys.stderr)

    sys.exit(0 if result["ok"] else 3)


if __name__ == "__main__":
    main()
